#ifndef ESPNOW_CONFIG_H
#define ESPNOW_CONFIG_H

#include <Arduino.h>
#include <ArduinoJson.h>

/**
 * ESP-NOW Configuration Management
 * Handles dynamic role assignment and device identity
 */
class ESPNowConfig {
private:
    // Auto-generated device identity
    String deviceMAC;
    String deviceChipID;
    uint8_t autoSensorID;
    String autoSensorName;
    
    // User configurable
    bool isMasterMode;
    bool isSlaveMode;
    String customSensorName;
    uint8_t customSensorID;
    bool useAutoID;
    bool useAutoName;
    
    // Network settings
    uint8_t transmissionPower;
    uint32_t sendInterval;
    bool enableSleep;
    
    void generateAutoIdentity();
    
public:
    ESPNowConfig();
    
    // Initialization
    void initialize();
    
    // Role management
    void setMasterMode(bool enabled);
    void setSlaveMode(bool enabled);
    bool isMaster() const { return isMasterMode; }
    bool isSlave() const { return isSlaveMode; }
    
    // Identity management
    uint8_t getSensorID() const;
    String getSensorName() const;
    void setCustomSensorID(uint8_t id);
    void setCustomSensorName(const String& name);
    void useAutoGeneratedID(bool use) { useAutoID = use; }
    void useAutoGeneratedName(bool use) { useAutoName = use; }
    
    // Device info (read-only)
    String getDeviceMAC() const { return deviceMAC; }
    String getDeviceChipID() const { return deviceChipID; }
    uint8_t getAutoSensorID() const { return autoSensorID; }
    String getAutoSensorName() const { return autoSensorName; }
    
    // Network settings
    void setTransmissionPower(uint8_t power) { transmissionPower = power; }
    void setSendInterval(uint32_t interval) { sendInterval = interval; }
    void setSleepEnabled(bool enabled) { enableSleep = enabled; }
    
    uint8_t getTransmissionPower() const { return transmissionPower; }
    uint32_t getSendInterval() const { return sendInterval; }
    bool isSleepEnabled() const { return enableSleep; }
    
    // JSON serialization
    void toJson(JsonObject& json) const;
    void fromJson(const JsonObject& json);
    String toJsonString() const;
    bool fromJsonString(const String& json);
    
    // Configuration validation
    bool isValid() const;
    String getValidationError() const;
};

#endif // ESPNOW_CONFIG_H